
CREATE DATABASE [USER DATA]

 CREATE TABLE [USER]
	 (
		FistName NVARCHAR(255)
		,MiddleName NVARCHAR(255)
		,LastName NVARCHAR(255)
		,UserID int NOT NULL PRIMARY KEY
		,[Address] NVARCHAR(255)
		,Account  NVARCHAR(255) UNIQUE
		,Sex bit 
	 )	

 CREATE TABLE ADMIN
	(
		UserID int REFERENCES [USER](UserID)
		,ID int NOT NULL PRIMARY KEY
		,Time Date 
	)
	
		
 CREATE TABLE MEMBER
	(
		UserID int REFERENCES [USER](UserID)
		,TypeMember NVARCHAR(255)
	)

 CREATE TABLE MEDIACONTENT
	(
		MediaID int NOT NULL PRIMARY KEY
		,Subject NVARCHAR(255)
		,Content NVARCHAR(255)
		,UserID int REFERENCES [USER](UserID)
	)

 CREATE TABLE GUEST
	(
		GuestID int NOT NULL PRIMARY KEY
		,Address NVARCHAR(255)
		,Time DATETIME
	)

 CREATE TABLE SHARE 
	(
		UserID int REFERENCES [USER](UserID)
		,MediaID int REFERENCES MEDIACONTENT(MediaID)
		,ShareID int NOT NULL PRIMARY KEY
	)

 CREATE TABLE COMMENT
	(
		UserID int REFERENCES [USER](UserID)
		,MediaID int REFERENCES MEDIACONTENT(MediaID)
		,CommentID int NOT NULL PRIMARY KEY
		,CommentText NVARCHAR(255)
	)

 CREATE TABLE EDIT
	(
		UserID int REFERENCES [USER](UserID)
		,MediaID int REFERENCES MEDIACONTENT(MediaID)
		,EditID int NOT NULL PRIMARY KEY
		,EditNote NVARCHAR(255)
)

 CREATE TABLE [READ] 
	(
		GuestID int REFERENCES GUEST(GuestID)
		,MediaID int REFERENCES MEDIACONTENT(MediaID)
		,ReadID int NOT NULL PRIMARY KEY
	)