
INSERT INTO [USER]
VALUES ('Trinh','Van','Phong',1,'Ha Noi','Account1',1)

INSERT INTO [USER]
VALUES ('Le','Thi','Ha',2,'Ha Noi','Account2',0)

INSERT INTO [USER]
VALUES ('Hoang','Thi','Hai',3,'Sai Gon','Account3',0)

INSERT INTO [USER]
VALUES ('Trinh','Van','Nam',4,'Hung Yen','Account4',1)

INSERT INTO [USER]
VALUES ('Do','Thi','Tam',5,'Thai Nguyen','Account5',0)

INSERT INTO [USER]
VALUES ('Hoang','Van','Thang',6,'Bac Giang','Account6',1)

INSERT INTO [ADMIN]
VALUES (1,1, '2015-01-01')

INSERT INTO [ADMIN]
VALUES (4,2, '2016-01-01')

INSERT INTO [ADMIN]
VALUES (5,3, '2017-01-01')

INSERT INTO [MEMBER]
VALUES (1,'VIP')

INSERT INTO [MEMBER]
VALUES (2,'VVIP')

INSERT INTO [MEMBER]
VALUES (3,'LIMIT')

INSERT INTO [MEMBER]
VALUES (4,'VIP')

INSERT INTO [MEMBER]
VALUES (5,'NORMAL')

INSERT INTO [MEMBER]
VALUES (6,'VIP')

INSERT INTO MEDIACONTENT
VALUES (1,'Tai lieu 1','link file',3)

INSERT INTO MEDIACONTENT
VALUES (2,'Tai lieu 2','link file',3)

INSERT INTO MEDIACONTENT
VALUES (3,'Tai lieu 3','link file',1)

INSERT INTO MEDIACONTENT
VALUES (4,'Tai lieu 4','link file',4)


INSERT INTO MEDIACONTENT
VALUES (5,'Tai lieu 5','link file',2)


INSERT INTO GUEST
VALUES (1,'Ha Noi','03:23pm')


INSERT INTO GUEST
VALUES (2,'Ha Nam','08:23am')


INSERT INTO GUEST
VALUES (3,'Quang Nam','09:13am')


INSERT INTO GUEST
VALUES (4,'Sai Gon','08:29am')


INSERT INTO SHARE
VALUES (2,2,1)

INSERT INTO SHARE
VALUES (3,4,2)

INSERT INTO SHARE
VALUES (1,2,3)

INSERT INTO SHARE
VALUES (2,1,4)

INSERT INTO COMMENT
VALUES (2,2,1,'good')

INSERT INTO COMMENT
VALUES (2,4,2,'very good')

INSERT INTO COMMENT
VALUES (1,4,3,'not use')

INSERT INTO COMMENT
VALUES (2,2,4,'very bad')


INSERT INTO EDIT
VALUES (2,2,1,'Error')

INSERT INTO EDIT
VALUES (2,1,2,'Bad')

INSERT INTO EDIT
VALUES (5,4,3,'delete')

INSERT INTO [READ]
VALUES (1,1,2)

INSERT INTO [READ]
VALUES (1,2,3)


INSERT INTO [READ]
VALUES (3,2,4)